name: build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build the Docker image
      run: docker build src/LiteDbComponent --tag rosenkolev/dapr-pluggable-component-litedb:${{ github.event.release.tag_name }} --tag rosenkolev/dapr-pluggable-component-litedb:latest
    - uses: docker/login-action@v3.0.0
      with:
        username: rosenkolev
        password: ${{ secrets.DOCKER_SECRET }}
    - name: Push the Docker image
      run: docker push -a rosenkolev/dopless
